"""Content generator — turns research, directives, and knowledge into publishable output.

Takes raw task results, knowledge graph data, and memories, then produces
formatted reports using templates and LLM synthesis.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from core.content.templates import ReportTemplate, REPORT_TEMPLATES, get_template

logger = logging.getLogger(__name__)


@dataclass
class ContentSection:
    """A single section of generated content."""
    title: str = ""
    content: str = ""
    word_count: int = 0
    sources: list[str] = field(default_factory=list)


@dataclass
class GeneratedContent:
    """Complete generated content output."""
    title: str = ""
    template_used: str = ""
    sections: list[ContentSection] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)
    total_words: int = 0
    total_cost: float = 0.0
    generated_at: str = ""

    # Full rendered output
    markdown: str = ""
    html: str = ""

    def render_markdown(self) -> str:
        """Render all sections as markdown."""
        parts = [f"# {self.title}\n"]
        parts.append(f"*Generated by Empire AI — {self.generated_at[:10]}*\n")

        for section in self.sections:
            parts.append(f"\n## {section.title}\n")
            parts.append(section.content)
            if section.sources:
                parts.append(f"\n*Sources: {', '.join(section.sources[:5])}*")

        parts.append(f"\n---\n*{self.total_words} words | Cost: ${self.total_cost:.4f} | Template: {self.template_used}*")

        self.markdown = "\n".join(parts)
        return self.markdown

    def render_html(self) -> str:
        """Render as simple HTML."""
        parts = [
            '<!DOCTYPE html><html><head>',
            f'<title>{self.title}</title>',
            '<style>body{font-family:system-ui;max-width:800px;margin:2rem auto;padding:0 1rem;line-height:1.7;color:#1a1a2e}',
            'h1{border-bottom:2px solid #e0e0e0;padding-bottom:0.5rem}',
            'h2{color:#2d3436;margin-top:2rem}',
            '.meta{color:#636e72;font-size:0.85rem;margin-bottom:2rem}',
            '.sources{color:#636e72;font-size:0.8rem;font-style:italic}',
            '.footer{border-top:1px solid #e0e0e0;margin-top:2rem;padding-top:1rem;color:#636e72;font-size:0.8rem}',
            '</style></head><body>',
            f'<h1>{self.title}</h1>',
            f'<p class="meta">Generated by Empire AI — {self.generated_at[:10]}</p>',
        ]

        for section in self.sections:
            parts.append(f'<h2>{section.title}</h2>')
            # Convert markdown-ish content to basic HTML
            content_html = section.content.replace('\n\n', '</p><p>').replace('\n', '<br>')
            content_html = content_html.replace('**', '<strong>').replace('**', '</strong>')
            parts.append(f'<p>{content_html}</p>')
            if section.sources:
                parts.append(f'<p class="sources">Sources: {", ".join(section.sources[:5])}</p>')

        parts.append(f'<div class="footer">{self.total_words} words | Cost: ${self.total_cost:.4f} | Template: {self.template_used}</div>')
        parts.append('</body></html>')

        self.html = '\n'.join(parts)
        return self.html


class ContentGenerator:
    """Generates formatted content from Empire's knowledge.

    Takes a topic + template, pulls relevant data from memory and
    knowledge graph, and uses LLM to produce polished output.
    """

    def __init__(self, empire_id: str = ""):
        self.empire_id = empire_id

    def generate(
        self,
        topic: str,
        template_name: str = "research_briefing",
        additional_context: str = "",
        max_tokens_per_section: int = 2000,
    ) -> GeneratedContent:
        """Generate content from a topic and template.

        Args:
            topic: The topic to write about.
            template_name: Which template to use.
            additional_context: Extra context to inject.
            max_tokens_per_section: Max tokens per section.

        Returns:
            GeneratedContent with rendered output.
        """
        template = get_template(template_name)
        if not template:
            template = REPORT_TEMPLATES["research_briefing"]
            template_name = "research_briefing"

        content = GeneratedContent(
            title=topic,
            template_used=template_name,
            generated_at=datetime.now(timezone.utc).isoformat(),
        )

        # Gather context from Empire's knowledge
        context = self._gather_context(topic)

        # Generate each section
        for section_def in template.sections:
            section = self._generate_section(
                topic=topic,
                section_name=section_def["name"],
                section_prompt=section_def["prompt"],
                system_prompt=template.system_prompt,
                context=context,
                additional_context=additional_context,
                max_tokens=max_tokens_per_section,
            )
            content.sections.append(section)
            content.total_words += section.word_count
            content.total_cost += 0  # Cost tracked via router

        # Render
        content.render_markdown()
        content.render_html()

        logger.info("Generated '%s': %d sections, %d words", topic, len(content.sections), content.total_words)
        return content

    def generate_from_directive(self, directive_id: str, template_name: str = "research_briefing") -> GeneratedContent:
        """Generate content from a completed directive's results.

        Args:
            directive_id: Completed directive to use.
            template_name: Template for formatting.

        Returns:
            GeneratedContent.
        """
        # Get directive report
        try:
            from db.engine import get_session
            from db.repositories.directive import DirectiveRepository
            from db.repositories.task import TaskRepository

            session = get_session()
            dir_repo = DirectiveRepository(session)
            task_repo = TaskRepository(session)

            directive = dir_repo.get(directive_id)
            if not directive:
                return GeneratedContent(title="Error", metadata={"error": "Directive not found"})

            tasks = task_repo.get_by_directive(directive_id)

            # Build context from task outputs
            task_context = "\n\n---\n\n".join(
                f"## {t.title}\n{(t.output_json or {}).get('content', '')[:3000]}"
                for t in tasks if t.status == "completed"
            )

            return self.generate(
                topic=directive.title,
                template_name=template_name,
                additional_context=task_context,
            )

        except Exception as e:
            logger.error("Failed to generate from directive: %s", e)
            return GeneratedContent(title="Error", metadata={"error": str(e)})

    def generate_status_report(self) -> GeneratedContent:
        """Generate an Empire status report from current system state."""
        # Gather system stats
        context_parts = []

        try:
            from core.memory.manager import MemoryManager
            mm = MemoryManager(self.empire_id)
            stats = mm.get_stats()
            context_parts.append(f"Memory: {stats.total_count} entries, avg importance {stats.avg_importance:.2f}")
        except Exception:
            pass

        try:
            from core.knowledge.graph import KnowledgeGraph
            graph = KnowledgeGraph(self.empire_id)
            kg_stats = graph.get_stats()
            context_parts.append(f"Knowledge graph: {kg_stats.entity_count} entities, {kg_stats.relation_count} relations")
        except Exception:
            pass

        try:
            from core.routing.budget import BudgetManager
            bm = BudgetManager(self.empire_id)
            context_parts.append(f"Budget: ${bm.get_daily_spend():.4f} daily, ${bm.get_monthly_spend():.4f} monthly")
        except Exception:
            pass

        try:
            from db.engine import get_session
            from db.repositories.lieutenant import LieutenantRepository
            session = get_session()
            repo = LieutenantRepository(session)
            fleet = repo.get_fleet_summary(self.empire_id)
            context_parts.append(f"Lieutenants: {fleet.get('total_lieutenants', 0)} total, {fleet.get('by_status', {}).get('active', 0)} active")
        except Exception:
            pass

        system_context = "\n".join(context_parts)

        return self.generate(
            topic="Empire AI Status Report",
            template_name="status_report",
            additional_context=f"Current system state:\n{system_context}",
        )

    def _gather_context(self, topic: str) -> str:
        """Gather relevant context from memory and knowledge graph."""
        parts = []

        # Memory context
        try:
            from core.memory.manager import MemoryManager
            mm = MemoryManager(self.empire_id)
            context = mm.get_context_window(query=topic, token_budget=3000)
            if context:
                parts.append(context)
        except Exception:
            pass

        # Knowledge graph context
        try:
            from core.knowledge.query import KnowledgeQuerier
            querier = KnowledgeQuerier(self.empire_id)
            answer = querier.ask(topic, depth=1)
            if answer.entity_name:
                kg_text = answer.to_prompt()
                parts.append(kg_text)
        except Exception:
            pass

        return "\n\n".join(parts) if parts else ""

    def _generate_section(
        self,
        topic: str,
        section_name: str,
        section_prompt: str,
        system_prompt: str,
        context: str,
        additional_context: str = "",
        max_tokens: int = 2000,
    ) -> ContentSection:
        """Generate a single section of content."""
        from llm.base import LLMRequest, LLMMessage
        from llm.router import ModelRouter, TaskMetadata

        router = ModelRouter()

        prompt = f"""You are writing the "{section_name}" section of a report on: {topic}

{section_prompt}

"""
        if context:
            prompt += f"""## Context from Empire's Knowledge
{context[:4000]}

"""
        if additional_context:
            prompt += f"""## Additional Research
{additional_context[:4000]}

"""

        prompt += """Write this section now. Be specific, thorough, and well-structured. Use markdown formatting."""

        try:
            request = LLMRequest(
                messages=[LLMMessage.user(prompt)],
                system_prompt=system_prompt,
                temperature=0.4,
                max_tokens=max_tokens,
            )
            response = router.execute(request, TaskMetadata(task_type="creative", complexity="complex"))

            return ContentSection(
                title=section_name,
                content=response.content,
                word_count=len(response.content.split()),
            )

        except Exception as e:
            logger.error("Section generation failed: %s", e)
            return ContentSection(
                title=section_name,
                content=f"*Section generation failed: {e}*",
                word_count=0,
            )

    def list_templates(self) -> list[dict]:
        """List available templates."""
        from core.content.templates import list_templates
        return list_templates()
