"""Content generator — turns research, directives, and knowledge into publishable output.

Takes raw task results, knowledge graph data, and memories, then produces
formatted reports using templates and LLM synthesis.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from typing import Any

import markdown as md_lib

from core.content.templates import ReportTemplate, REPORT_TEMPLATES, get_template

logger = logging.getLogger(__name__)


@dataclass
class ContentSection:
    """A single section of generated content."""
    title: str = ""
    content: str = ""
    word_count: int = 0
    sources: list[str] = field(default_factory=list)
    cost_usd: float = 0.0


@dataclass
class GeneratedContent:
    """Complete generated content output."""
    id: str = ""
    title: str = ""
    template_used: str = ""
    sections: list[ContentSection] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)
    total_words: int = 0
    total_cost: float = 0.0
    generated_at: str = ""

    # Full rendered output
    markdown: str = ""
    html: str = ""

    def render_markdown(self) -> str:
        """Render all sections as markdown."""
        parts = [f"# {self.title}\n"]
        parts.append(f"*Generated by Empire AI — {self.generated_at[:10]}*\n")

        for section in self.sections:
            parts.append(f"\n## {section.title}\n")
            parts.append(section.content)
            if section.sources:
                parts.append(f"\n*Sources: {', '.join(section.sources[:5])}*")

        parts.append(f"\n---\n*{self.total_words} words | Cost: ${self.total_cost:.4f} | Template: {self.template_used}*")

        self.markdown = "\n".join(parts)
        return self.markdown

    def render_html(self) -> str:
        """Render as HTML using proper markdown parser."""
        if not self.markdown:
            self.render_markdown()

        # Use python-markdown for proper conversion
        body_html = md_lib.markdown(
            self.markdown,
            extensions=["tables", "fenced_code", "nl2br"],
        )

        self.html = f"""<!DOCTYPE html>
<html><head>
<title>{self.title}</title>
<style>
body {{ font-family: 'Inter', system-ui, sans-serif; max-width: 840px; margin: 2rem auto; padding: 0 1.5rem; line-height: 1.8; color: #1a1a2e; }}
h1 {{ font-size: 1.8rem; border-bottom: 2px solid #e0e0e0; padding-bottom: 0.5rem; }}
h2 {{ color: #2d3436; margin-top: 2.5rem; font-size: 1.3rem; }}
h3 {{ color: #636e72; margin-top: 1.5rem; }}
p {{ margin-bottom: 1rem; }}
ul, ol {{ margin-bottom: 1rem; padding-left: 1.5rem; }}
li {{ margin-bottom: 0.3rem; }}
strong {{ color: #2d3436; }}
em {{ color: #636e72; }}
code {{ background: #f1f2f6; padding: 0.15rem 0.4rem; border-radius: 3px; font-size: 0.9rem; }}
pre {{ background: #f1f2f6; padding: 1rem; border-radius: 6px; overflow-x: auto; }}
pre code {{ background: none; padding: 0; }}
table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
th, td {{ border: 1px solid #dfe6e9; padding: 0.5rem 0.75rem; text-align: left; }}
th {{ background: #f1f2f6; font-weight: 600; }}
hr {{ border: none; border-top: 1px solid #dfe6e9; margin: 2rem 0; }}
blockquote {{ border-left: 3px solid #74b9ff; padding-left: 1rem; color: #636e72; margin: 1rem 0; }}
</style>
</head><body>
{body_html}
</body></html>"""
        return self.html


class ContentGenerator:
    """Generates formatted content from Empire's knowledge.

    Takes a topic + template, pulls relevant data from memory and
    knowledge graph, and uses LLM to produce polished output.
    """

    def __init__(self, empire_id: str = ""):
        self.empire_id = empire_id

    def generate(
        self,
        topic: str,
        template_name: str = "research_briefing",
        additional_context: str = "",
        max_tokens_per_section: int = 2000,
    ) -> GeneratedContent:
        """Generate content from a topic and template.

        Args:
            topic: The topic to write about.
            template_name: Which template to use.
            additional_context: Extra context to inject.
            max_tokens_per_section: Max tokens per section.

        Returns:
            GeneratedContent with rendered output.
        """
        template = get_template(template_name)
        if not template:
            template = REPORT_TEMPLATES["research_briefing"]
            template_name = "research_briefing"

        from utils.crypto import generate_id
        content = GeneratedContent(
            id=generate_id("rpt_"),
            title=topic,
            template_used=template_name,
            generated_at=datetime.now(timezone.utc).isoformat(),
        )

        # Gather context from Empire's knowledge
        context = self._gather_context(topic, template_name)

        # Generate each section
        total_cost = 0.0
        for section_def in template.sections:
            section = self._generate_section(
                topic=topic,
                section_name=section_def["name"],
                section_prompt=section_def["prompt"],
                system_prompt=template.system_prompt,
                context=context,
                additional_context=additional_context,
                max_tokens=max_tokens_per_section,
            )
            content.sections.append(section)
            content.total_words += section.word_count
            total_cost += section.cost_usd

        content.total_cost = total_cost

        # Render
        content.render_markdown()
        content.render_html()

        # Store in DB
        self._store_content(content)

        logger.info("Generated '%s': %d sections, %d words, $%.4f", topic, len(content.sections), content.total_words, total_cost)
        return content

    def generate_from_directive(self, directive_id: str, template_name: str = "research_briefing") -> GeneratedContent:
        """Generate content from a completed directive's results."""
        try:
            from db.engine import get_session
            from db.repositories.directive import DirectiveRepository
            from db.repositories.task import TaskRepository

            session = get_session()
            dir_repo = DirectiveRepository(session)
            task_repo = TaskRepository(session)

            directive = dir_repo.get(directive_id)
            if not directive:
                return GeneratedContent(title="Error", metadata={"error": "Directive not found"})

            tasks = task_repo.get_by_directive(directive_id)

            # Build context from task outputs
            task_context = "\n\n---\n\n".join(
                f"## {t.title}\n{(t.output_json or {}).get('content', '')[:3000]}"
                for t in tasks if t.status == "completed"
            )

            if not task_context:
                task_context = f"Directive: {directive.title}\nDescription: {directive.description}\n(No completed tasks found — generating from description)"

            return self.generate(
                topic=directive.title,
                template_name=template_name,
                additional_context=task_context,
            )

        except Exception as e:
            logger.error("Failed to generate from directive: %s", e)
            return GeneratedContent(title="Error", metadata={"error": str(e)})

    def generate_status_report(self) -> GeneratedContent:
        """Generate an Empire status report from current system state."""
        context_parts = []

        try:
            from core.memory.manager import MemoryManager
            mm = MemoryManager(self.empire_id)
            stats = mm.get_stats()
            context_parts.append(f"Memory: {stats.total_count} entries, avg importance {stats.avg_importance:.2f}, avg decay {stats.avg_decay:.2f}")
        except Exception:
            pass

        try:
            from core.knowledge.graph import KnowledgeGraph
            graph = KnowledgeGraph(self.empire_id)
            kg_stats = graph.get_stats()
            context_parts.append(f"Knowledge graph: {kg_stats.entity_count} entities, {kg_stats.relation_count} relations, avg confidence {kg_stats.avg_confidence:.2f}")
            context_parts.append(f"Entity types: {kg_stats.entity_types}")
        except Exception:
            pass

        try:
            from core.routing.budget import BudgetManager
            bm = BudgetManager(self.empire_id)
            context_parts.append(f"Budget: ${bm.get_daily_spend():.4f} daily (${bm.get_remaining_daily():.2f} remaining), ${bm.get_monthly_spend():.4f} monthly")
        except Exception:
            pass

        try:
            from db.engine import get_session
            from db.repositories.lieutenant import LieutenantRepository
            session = get_session()
            repo = LieutenantRepository(session)
            fleet = repo.get_fleet_summary(self.empire_id)
            context_parts.append(f"Lieutenants: {fleet.get('total_lieutenants', 0)} total, {fleet.get('by_status', {}).get('active', 0)} active, avg performance {fleet.get('avg_performance', 0):.2f}")
        except Exception:
            pass

        try:
            from core.memory.compression import MemoryCompressor
            compressor = MemoryCompressor(self.empire_id)
            comp_stats = compressor.get_compression_stats()
            context_parts.append(f"Compression: {comp_stats.get('compressed_summaries', 0)} summaries, {comp_stats.get('archived_originals', 0)} archived")
        except Exception:
            pass

        system_context = "\n".join(f"- {p}" for p in context_parts)

        return self.generate(
            topic="Empire AI Status Report",
            template_name="status_report",
            additional_context=f"## Current System State (REAL DATA — use these exact numbers)\n{system_context}",
        )

    def generate_weekly_digest(self) -> GeneratedContent:
        """Generate a weekly AI digest from the last 7 days of knowledge."""
        # Get memories from last 7 days
        from core.memory.manager import MemoryManager
        mm = MemoryManager(self.empire_id)

        week_ago = (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()
        recent = mm.recall(query="AI model release agent news", limit=30)

        # Filter to last 7 days
        weekly_memories = []
        for mem in recent:
            created = mem.get("created_at", "")
            if created and created >= week_ago:
                weekly_memories.append(mem)

        weekly_context = "\n".join(
            f"- [{m.get('created_at', '')[:10]}] {m.get('title', '')}: {m.get('content', '')[:200]}"
            for m in weekly_memories[:20]
        )

        return self.generate(
            topic=f"Weekly AI Digest — {datetime.now(timezone.utc).strftime('%B %d, %Y')}",
            template_name="weekly_digest",
            additional_context=f"## Events from the past 7 days\n{weekly_context}" if weekly_context else "",
        )

    def get_stored_reports(self, limit: int = 10) -> list[dict]:
        """Get previously generated reports from memory."""
        try:
            from db.engine import get_session
            from db.models import MemoryEntry
            from sqlalchemy import select

            session = get_session()
            stmt = (
                select(MemoryEntry)
                .where(MemoryEntry.empire_id == self.empire_id)
                .where(MemoryEntry.category == "generated_report")
                .order_by(MemoryEntry.created_at.desc())
                .limit(limit)
            )
            entries = list(session.execute(stmt).scalars().all())

            return [
                {
                    "title": e.title,
                    "created_at": e.created_at.isoformat() if e.created_at else None,
                    "metadata": e.metadata_json,
                    "preview": e.content[:300] if e.content else "",
                }
                for e in entries
            ]
        except Exception as e:
            logger.warning("Failed to get stored reports: %s", e)
            return []

    def _gather_context(self, topic: str, template_name: str = "") -> str:
        """Gather relevant context from memory and knowledge graph."""
        parts = []

        # Memory context
        try:
            from core.memory.manager import MemoryManager
            mm = MemoryManager(self.empire_id)
            context = mm.get_context_window(query=topic, token_budget=3000)
            if context:
                parts.append(context)
        except Exception:
            pass

        # Knowledge graph context
        try:
            from core.knowledge.query import KnowledgeQuerier
            querier = KnowledgeQuerier(self.empire_id)
            answer = querier.ask(topic, depth=1)
            if answer.entity_name:
                kg_text = answer.to_prompt()
                parts.append(kg_text)
        except Exception:
            pass

        return "\n\n".join(parts) if parts else ""

    def _generate_section(
        self,
        topic: str,
        section_name: str,
        section_prompt: str,
        system_prompt: str,
        context: str,
        additional_context: str = "",
        max_tokens: int = 2000,
    ) -> ContentSection:
        """Generate a single section of content."""
        from llm.base import LLMRequest, LLMMessage
        from llm.router import ModelRouter, TaskMetadata

        router = ModelRouter()

        prompt = f"""You are writing the "{section_name}" section of a report on: {topic}

{section_prompt}

"""
        if context:
            prompt += f"""## Context from Empire's Knowledge
{context[:4000]}

"""
        if additional_context:
            prompt += f"""## Additional Research
{additional_context[:4000]}

"""

        prompt += """Write this section now. Be specific, thorough, and well-structured. Use markdown formatting (headers, bullets, bold, tables where appropriate)."""

        try:
            request = LLMRequest(
                messages=[LLMMessage.user(prompt)],
                system_prompt=system_prompt,
                temperature=0.4,
                max_tokens=max_tokens,
            )
            response = router.execute(request, TaskMetadata(task_type="creative", complexity="complex"))

            return ContentSection(
                title=section_name,
                content=response.content,
                word_count=len(response.content.split()),
                cost_usd=response.cost_usd,
            )

        except Exception as e:
            logger.error("Section generation failed: %s", e)
            return ContentSection(
                title=section_name,
                content=f"*Section generation failed: {e}*",
                word_count=0,
            )

    def _store_content(self, content: GeneratedContent) -> None:
        """Store generated content in memory for later retrieval."""
        try:
            from core.memory.manager import MemoryManager
            mm = MemoryManager(self.empire_id)
            mm.store(
                content=content.markdown[:8000],
                memory_type="semantic",
                title=f"Report: {content.title[:80]}",
                category="generated_report",
                importance=0.7,
                tags=["report", content.template_used, "generated"],
                source_type="content_generator",
                metadata={
                    "content_type": "report",
                    "report_id": content.id,
                    "template": content.template_used,
                    "total_words": content.total_words,
                    "total_cost": content.total_cost,
                    "sections": len(content.sections),
                    "generated_at": content.generated_at,
                },
            )
        except Exception as e:
            logger.warning("Failed to store generated content: %s", e)

    def list_templates(self) -> list[dict]:
        """List available templates."""
        from core.content.templates import list_templates
        return list_templates()
